# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://docs.hugoblox.com/reference/language/

# Default language
en:
  languageCode: en-us
  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
  contentDir: content/en
  title: hayoung's English website title...
  params:
    # Open Graph 설정
    opengraph:
      type: website
      image: "/blackback.jpg"  # 대표 이미지 경로
  manu:
    - name: Bio
      url: /
      weight: 10

    - name: Experience
      url: experience/
      weight: 20

    - name: Papers
      url: /#papers
      weight: 11

    - name: Talks
      url: /#talks
      weight: 12

    - name: My post
      url: /#news
      weight: 13


    - name: Projects
      identifier: tags
      weight: 30
    - name: NORTH
      parent: tags
      url: project/north/
      weight: 31
    - name: bulletin
      parent: tags
      url: project/bulletin/
      weight: 31

    - name: Contact
      url: contact/
      weight: 40

    - name: slider
      url: slides/
      weight: 50

# Uncomment the lines below to configure your website in a second language.
ko:
  languageCode: ko
  contentDir: content/ko
  title: hayoung's korean website title...
  params:
    description: Site description in korean...