# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://docs.hugoblox.com/reference/language/

# Default language
en:
  languageCode: en-us
  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
  contentDir: content/en
  title: English website title...
  params:
    description: Site description in english...

# Uncomment the lines below to configure your website in a second language.
ko:
  languageCode: ko
  contentDir: content/ko
  title: korean website title...
  params:
    description: Site description in korean...
  menu:
    main:
      - name: 한국어
        url: '#about'
        weight: 1
