# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://docs.hugoblox.com/reference/language/

# Default language
en:
  languageCode: en-us
  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
  contentDir: content/en
  title: English website title...
  params:
    description: Site description in english...

# Uncomment the lines below to configure your website in a second language.
ko:
  languageCode: ko
  contentDir: content/ko
  title: korean website title...
  params:
    description: Site description in korean...
  menu:
    main:
      - name: Bio
        url: ko/portfolio/
        weight: 10

      - name: 기사
        url: /ko/portfolio/#papers
        weight: 11

      - name: Talks
        url: /ko/portfolio/#talks
        weight: 12

      - name: 뉴스
        url: /ko/portfolio/#news
        identifier: news
        weight: 13
      - name: conference-paper
        parent: news
        url: /ko/portfolio/publication/conference-paper
        weight: 14

      - name: 활동경력
        url: ko/portfolio/experience/
        weight: 20

      - name: 프로젝트
        identifier: tags
        weight: 30
      - name: NORTH
        parent: tags
        url: ko/portfolio/project/north/
        weight: 31

      - name: Teaching
        url: ko/portfolio/teaching/
        weight: 40
