# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://docs.hugoblox.com/reference/language/

# Default language
en:
  languageCode: en-us
  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
  contentDir: content/en
  title: hayoung's English website title...
  params:
    # Open Graph 설정
    opengraph:
      type: website
      image: "/blackback.jpg"  # 대표 이미지 경로
  manu:
    - name: Bio
      url: /en/
      weight: 10

    - name: Experience
      url: experience/en/
      weight: 20

    - name: Papers
      url: /#paper/en
      weight: 11

    - name: Talks
      url: /#talks/en
      weight: 12

    - name: My post
      url: /#news/en
      weight: 13

    - name: Projects
      identifier: tags
      weight: 30
    - name: NORTH
      parent: tags
      url: en/project/north/
      weight: 31
    - name: bulletin
      parent: tags
      url: en/project/bulletin/
      weight: 31

    - name: Contact
      url: en/contact/
      weight: 40

    - name: slider
      url: en/slides/
      weight: 50

# Uncomment the lines below to configure your website in a second language.
ko:
  languageCode: ko
  contentDir: content/ko
  title: hayoung's korean website title...
  params:
    description: Site description in korean...